# Generated by Django 6.1 on 2026-10-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelaria_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
